import React, { useState, useEffect, useRef, useCallback } from "react";
import { createRoot } from "react-dom/client";
import {
  ArrowUpRight,
  ArrowRight,
  ArrowLeft,
  ChevronRight,
  Check,
  Monitor,
  LayoutGrid,
  Folder,
  Settings,
  ShieldCheck,
  Wifi,
  Plus,
  Search,
  MoreHorizontal,
  Keyboard,
  MousePointer2,
  Hand,
  Maximize2,
  Minus,
  X,
  Lock,
  Power,
  RotateCw,
  Link2,
  Smartphone,
  Copy,
  Download,
  FileText,
  Image,
  File,
  CornerDownLeft,
  Command,
  Undo2,
  LoaderCircle,
  AlertCircle,
  CheckCircle2,
  RefreshCw,
  LogOut,
  Signal,
  Play,
  Share2,
  Eye,
  ChevronDown,
  Home,
} from "lucide-react";
import QRCode from "qrcode";
import { handShapes } from "../brand.js";
import "../styles.css";

const DEMO = new URLSearchParams(location.search).has("demo");
const demoApps = [
  {
    name: "Safari",
    bundleId: "demo.safari",
    active: true,
    windows: [{ id: 1, title: "Your next big idea" }],
  },
  {
    name: "Notes",
    bundleId: "demo.notes",
    windows: [{ id: 2, title: "A little room to think" }],
  },
  { name: "Finder", bundleId: "demo.finder", windows: [] },
  { name: "Calendar", bundleId: "demo.calendar", windows: [] },
  { name: "Music", bundleId: "demo.music", windows: [] },
  { name: "Messages", bundleId: "demo.messages", windows: [] },
];
const demoFiles = [
  {
    name: "Welcome to Palm.txt",
    path: "Welcome.txt",
    size: 704,
    modified: "2026-09-22",
    directory: false,
  },
  { name: "Project notes", path: "notes", size: 0, directory: true },
];
async function api(path, body) {
  const r = await fetch("/api/" + path, {
    method: body === undefined ? "GET" : "POST",
    headers: body === undefined ? {} : { "Content-Type": "application/json" },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const x = await r.json();
  if (!r.ok) throw new Error(x.error || "Could not reach your Mac.");
  return x;
}
// A 36-second demo made with Remotion (video/), shown muted on the setup
// page. With reduced motion it waits for a tap instead of playing by itself.
function DemoVideo() {
  const reduced =
    typeof window !== "undefined" &&
    window.matchMedia?.("(prefers-reduced-motion: reduce)").matches;
  const ref = useRef(null);
  useEffect(() => {
    // React does not set the muted attribute before load, and browsers only
    // autoplay muted video, so mute and start it here.
    const video = ref.current;
    if (!video || reduced) return;
    video.muted = true;
    video.play().catch(() => {});
  }, [reduced]);
  return (
    <video
      ref={ref}
      className="welcome-video"
      src="/palm-demo.mp4"
      poster="/palm-demo-poster.jpg"
      autoPlay={!reduced}
      controls={reduced}
      muted
      loop
      playsInline
      preload={reduced ? "none" : "auto"}
      aria-label="Palm demo: agents, the live screen, terminal, files and Mac controls on an iPhone"
    />
  );
}

// Palm's hand (generated by scripts/render-brand.swift) on its graphite tile.
function Mark() {
  return (
    <span className="mark">
      <svg viewBox="0 0 1024 1024" aria-hidden="true" dangerouslySetInnerHTML={{ __html: handShapes }} />
    </span>
  );
}
function AppIcon({ app, size = "" }) {
  const initials = app.name.slice(0, 1);
  return app.icon ? (
    <img className={"app-icon " + size} src={app.icon} alt="" />
  ) : (
    <span
      className={
        "app-icon generated " +
        size +
        " icon-" +
        (app.bundleId || "").split(".").pop()
      }
    >
      {app.name === "Safari" ? (
        <span className="compass">↗</span>
      ) : app.name === "Finder" ? (
        "☻"
      ) : app.name === "Notes" ? (
        <FileText />
      ) : app.name === "Calendar" ? (
        <b>22</b>
      ) : app.name === "Music" ? (
        "♫"
      ) : app.name === "Messages" ? (
        "•••"
      ) : (
        initials
      )}
    </span>
  );
}
function FileIcon({ item }) {
  return (
    <span className={"file-icon " + (item.directory ? "folder" : "")}>
      {item.directory ? (
        <Folder size={20} />
      ) : /\.(png|jpg|jpeg|webp|heic)$/i.test(item.name) ? (
        <Image size={20} />
      ) : (
        <FileText size={20} />
      )}
    </span>
  );
}
function bytes(n) {
  return n < 1024
    ? `${n} B`
    : n < 1048576
      ? `${Math.round(n / 1024)} KB`
      : `${(n / 1048576).toFixed(1)} MB`;
}
function Button({
  children,
  onClick,
  secondary = false,
  disabled = false,
  className = "",
  ...props
}) {
  return (
    <button
      className={(secondary ? "button secondary" : "button") + " " + className}
      onClick={onClick}
      disabled={disabled}
      {...props}
    >
      {children}
    </button>
  );
}
function Modal({ title, children, onClose }) {
  const close = useRef();
  useEffect(() => {
    const prior = document.activeElement;
    close.current?.focus();
    const fn = (e) => {
      if (e.key === "Escape") onClose();
      if (e.key === "Tab") {
        const els = [
          ...document.querySelectorAll(
            ".modal button,.modal input,.modal a,.modal textarea",
          ),
        ].filter((x) => !x.disabled);
        if (els.length && e.shiftKey && document.activeElement === els[0]) {
          e.preventDefault();
          els.at(-1).focus();
        } else if (
          els.length &&
          !e.shiftKey &&
          document.activeElement === els.at(-1)
        ) {
          e.preventDefault();
          els[0].focus();
        }
      }
    };
    document.addEventListener("keydown", fn);
    return () => {
      document.removeEventListener("keydown", fn);
      prior?.focus();
    };
  }, []);
  return (
    <div
      className="modal-shade"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <section
        className="modal"
        role="dialog"
        aria-modal="true"
        aria-label={title}
      >
        <div className="section-head">
          <h2>{title}</h2>
          <button
            ref={close}
            className="icon-button"
            aria-label="Close"
            onClick={onClose}
          >
            <X />
          </button>
        </div>
        {children}
      </section>
    </div>
  );
}
function MacArt() {
  return (
    <div className="mac-art" aria-hidden="true">
      <div className="mac-screen">
        <div className="orb orb-a" />
        <div className="orb orb-b" />
        <div className="orb orb-c" />
        <div className="mac-menubar">
          <span>◒</span>
          <span>Finder</span>
          <span>File</span>
          <span>Edit</span>
          <i />
        </div>
        <div className="mac-dock">
          {["#62b7f0", "#e3e9ce", "#f6ca63", "#f07880", "#88bca5"].map((c) => (
            <span key={c} style={{ background: c }} />
          ))}
        </div>
      </div>
      <div className="mac-base" />
    </div>
  );
}

function App() {
  const [boot, setBoot] = useState(true),
    [paired, setPaired] = useState(DEMO),
    [local, setLocal] = useState(false),
    [status, setStatus] = useState(null),
    [apps, setApps] = useState([]),
    [files, setFiles] = useState([]),
    [tab, setTab] = useState("home"),
    [error, setError] = useState(""),
    [notice, setNotice] = useState(""),
    [modal, setModal] = useState(null),
    [setup, setSetup] = useState(null),
    [connectionOrigin, setConnectionOrigin] = useState(""),
    [pair, setPair] = useState(null),
    [qr, setQr] = useState(""),
    [busy, setBusy] = useState(false),
    [query, setQuery] = useState(""),
    [folder, setFolder] = useState(""),
    [code, setCode] = useState(""),
    [target, setTarget] = useState(null),
    [connected, setConnected] = useState(false);
  const demo = DEMO;
  const synthetic = status?.synthetic;
  const toast = useCallback((text) => {
    setNotice(text);
    setTimeout(() => setNotice(""), 4000);
  }, []);
  async function load() {
    if (demo) {
      setStatus({
        name: "Your MacBook Pro",
        screenPermission: true,
        controlPermission: true,
        sharedFolder: "Sample files",
        power: { lock: false },
        remoteEnabled: false,
        activeApp: "Safari",
      });
      setApps(demoApps);
      setFiles(demoFiles);
      setBoot(false);
      return;
    }
    try {
      const s = await api("session");
      setPaired(s.paired);
      setLocal(s.local);
      if (s.paired) {
        const [st, ap, fi] = await Promise.all([
          api("status"),
          api("apps"),
          api("files"),
        ]);
        setStatus(st);
        setApps(ap);
        setFiles(fi.items);
      } else if (s.local) {
        setSetup(await api("local/setup"));
      }
      setError("");
    } catch (e) {
      setError(e.message);
    } finally {
      setBoot(false);
    }
  }
  useEffect(() => {
    load();
    function readPairingLink() {
      const fragment = new URLSearchParams(location.hash.slice(1));
      if (!fragment.has("pair")) return;
      setCode(fragment.get("pair"));
      history.replaceState(null, "", location.pathname + location.search);
    }
    readPairingLink();
    window.addEventListener("hashchange", readPairingLink);
    return () => window.removeEventListener("hashchange", readPairingLink);
  }, []);
  useEffect(() => {
    if (!paired || demo) return;
    const t = setInterval(async () => {
      try {
        setStatus(await api("status"));
      } catch (e) {
        setError(e.message);
      }
    }, 15000);
    return () => clearInterval(t);
  }, [paired, demo]);
  async function connectLocal() {
    setBusy(true);
    try {
      await api("local/connect", {});
      await load();
    } catch (e) {
      setError(e.message);
    } finally {
      setBusy(false);
    }
  }
  async function submitPair(e) {
    e.preventDefault();
    setBusy(true);
    try {
      await api("pair", { code, name: "iPhone" });
      await load();
    } catch (e) {
      setError(e.message);
    } finally {
      setBusy(false);
    }
  }
  async function openSetup() {
    if (demo) {
      toast("Interface preview — connect your Mac to pair a phone.");
      return;
    }
    try {
      const next = await api("local/setup");
      setSetup(next);
      setConnectionOrigin(next.remoteOrigin || "");
      setModal("setup");
    } catch (e) {
      setError(e.message);
    }
  }
  async function pairPhone() {
    if (demo) return toast("Pairing is available when connected to your Mac.");
    try {
      setSetup(await api("local/setup"));
      const p = await api("local/pair-code", {});
      setPair(p);
      setQr(
        p.url
          ? await QRCode.toDataURL(p.url, {
              width: 240,
              margin: 2,
              color: { dark: "#13231a", light: "#ffffff" },
            })
          : "",
      );
      setModal("pair");
    } catch (e) {
      setError(e.message);
    }
  }
  async function permission(kind) {
    try {
      await api("local/permissions", { kind });
      toast("Finish the permission step in Mac System Settings.");
    } catch (e) {
      setError(e.message);
    }
  }
  async function openApp(app) {
    if (demo) {
      setTarget({ name: app.name, windowId: app.windows?.[0]?.id || 0 });
      setTab("control");
      return;
    }
    try {
      const r = await api("command", {
        op: "activate",
        bundleId: app.bundleId,
      });
      if (r.ok === false)
        throw new Error("The Mac could not bring that app forward.");
      if (!r.windowId)
        throw new Error(
          "This app has no visible window yet. Open a window on your Mac and try again.",
        );
      setTarget({ name: app.name, windowId: r.windowId });
      setTab("control");
    } catch (e) {
      setError(e.message);
    }
  }
  async function browse(path = "") {
    if (demo) return toast("These are sample files in the interface preview.");
    try {
      const x = await api("files?path=" + encodeURIComponent(path));
      setFiles(x.items);
      setFolder(path);
    } catch (e) {
      setError(e.message);
    }
  }
  async function shareFile(item) {
    if (demo) return toast("Connect your Mac to download your own files.");
    if (item.directory) return browse(item.path);
    const download = () => {
      const a = document.createElement("a");
      a.href = "/api/download?path=" + encodeURIComponent(item.path);
      a.download = item.name;
      a.click();
      toast("Download started.");
    };
    if (item.size > 25 * 1024 * 1024) {
      download();
      return;
    }
    try {
      const response = await fetch(
        "/api/download?path=" + encodeURIComponent(item.path),
      );
      if (!response.ok) throw new Error("Could not download this file.");
      const blob = await response.blob();
      const f = new window.File([blob], item.name, { type: blob.type });
      if (navigator.canShare?.({ files: [f] })) {
        await navigator.share({ files: [f] });
      } else {
        const url = URL.createObjectURL(blob),
          a = document.createElement("a");
        a.href = url;
        a.download = item.name;
        a.click();
        setTimeout(() => URL.revokeObjectURL(url), 30000);
        toast("File downloaded.");
      }
    } catch (e) {
      if (e.name === "NotAllowedError") download();
      else if (e.name !== "AbortError") setError(e.message);
    }
  }
  async function lockMac() {
    try {
      await api("command", { op: "lock", confirm: true });
      setModal(null);
      toast("Lock command sent.");
    } catch (e) {
      setError(e.message);
    }
  }
  function changeTab(next) {
    setTab(next);
    setQuery("");
    if (next === "files" && folder === "") browse("");
  }
  const sidebar = (
    <>
      <a className="brand" href="/" aria-label="Palm home">
        <Mark />
        <span>
          palm<span className="brand-dot">.</span>
        </span>
      </a>
      <div className="nav-label">YOUR WORKSPACE</div>
      <nav className="main-nav">
        {[
          ["home", Home, "Overview"],
          ["apps", LayoutGrid, "Apps"],
          ["files", Folder, "Files"],
          ["settings", Settings, "Settings"],
        ].map(([id, Icon, label]) => (
          <button
            key={id}
            className={tab === id ? "active" : ""}
            onClick={() => changeTab(id)}
          >
            <Icon size={20} />
            <span>{label}</span>
            {tab === id && <i />}
          </button>
        ))}
      </nav>
      <div className="sidebar-bottom">
        <div className="private-badge">
          <ShieldCheck size={18} />
          <span>Private to your paired devices</span>
        </div>
        <div className="sidebar-version">Palm 0.4</div>
      </div>
    </>
  );
  if (boot)
    return (
      <main className="loading">
        <Mark />
        <p>Opening Palm</p>
      </main>
    );
  if (!paired)
    return (
      <main className="welcome">
        <div className="welcome-brand">
          <Mark />
          <b>palm.</b>
        </div>
        <div className="welcome-layout">
          <section className="welcome-copy">
            <h1>Palm</h1>
            <p>
              Use this Mac from your iPhone: agents, terminal, files, previews
              and the live screen.
            </p>
            <DemoVideo />
          </section>
          <section className="welcome-card">
            <span className="step-icon">
              {local ? <Monitor /> : <Smartphone />}
            </span>
            <h2>
              {local
                ? "Set up Palm on this Mac"
                : "Connect to your Mac"}
            </h2>
            <p>
              {local
                ? "Open the setup here, then pair your iPhone from the Palm app."
                : "Enter the code shown in Palm on your Mac to connect this iPhone."}
            </p>
            {error && (
              <div className="alert">
                <AlertCircle size={18} />
                {error}
              </div>
            )}
            {local ? (
              <>
                <div className="setup-check">
                  <CheckCircle2 />
                  <span>
                    Mac companion <small>Ready on this computer</small>
                  </span>
                </div>
                <div className="setup-check">
                  <ShieldCheck />
                  <span>
                    Private by default{" "}
                    <small>Phone access is enabled during setup</small>
                  </span>
                </div>
                <Button onClick={connectLocal} disabled={busy}>
                  {busy ? (
                    <LoaderCircle className="spin" size={18} />
                  ) : (
                    <>
                      Open setup <ArrowRight size={18} />
                    </>
                  )}
                </Button>
                <p className="fine">
                  The first connection stays on this Mac. Screen sharing and
                  controls need macOS permission.
                </p>
              </>
            ) : (
              <form onSubmit={submitPair}>
                <label htmlFor="pair-code">PAIRING CODE</label>
                <input
                  id="pair-code"
                  className="code-input"
                  autoComplete="one-time-code"
                  autoCapitalize="characters"
                  placeholder="XXXXX XXXXX"
                  maxLength={12}
                  value={code}
                  onChange={(e) => setCode(e.target.value)}
                />
                <Button disabled={busy || code.replace(/\s/g, "").length < 10}>
                  Connect to my Mac <ArrowRight size={18} />
                </Button>
                <p className="fine">
                  Codes expire after two minutes. Only pair a computer you
                  trust.
                </p>
              </form>
            )}
          </section>
        </div>
      </main>
    );
  return (
    <div className="shell">
      <aside className="sidebar">{sidebar}</aside>
      <div className="workspace">
        <header className="topbar">
          <span className="breadcrumb">
            My workspace <ChevronRight size={14} />{" "}
            <b>
              {tab === "control"
                ? "Live control"
                : tab[0].toUpperCase() + tab.slice(1)}
            </b>
          </span>
          <span className={"connection-chip " + (demo ? "demo-chip" : "")}>
            <span className="tiny-dot" />
            {demo
              ? "Interface preview"
              : synthetic
                ? "Synthetic test host"
                : status?.remoteEnabled
                  ? "Private connection"
                  : "Local preview"}
          </span>
          <button
            className="avatar"
            onClick={local ? openSetup : () => changeTab("settings")}
            aria-label="Connection settings"
          >
            {demo ? "P" : "C"}
          </button>
        </header>
        {(demo || synthetic) && (
          <div className="demo-banner">
            <Eye size={14} />
            {demo
              ? "Interactive design preview. Sample apps and files; no computer is being controlled."
              : "Synthetic test host. This canvas does not show or control your Mac."}
            {demo && (
              <a href="/">
                Connect your Mac <ArrowUpRight size={13} />
              </a>
            )}
          </div>
        )}
        {error && (
          <div className="error-bar" role="alert">
            <AlertCircle size={18} />
            <span>{error}</span>
            <button
              className="icon-button"
              onClick={() => setError("")}
              aria-label="Dismiss error"
            >
              <X size={16} />
            </button>
          </div>
        )}
        <main
          className={"content " + (tab === "control" ? "control-content" : "")}
        >
          {tab === "home" && (
            <>
              <div className="page-heading">
                <div>
                  <h1>Overview</h1>
                </div>
                <button
                  className="icon-button heading-refresh"
                  onClick={load}
                  aria-label="Refresh workspace"
                >
                  <RefreshCw size={18} />
                </button>
              </div>
              <div className="overview-grid">
                <div className="overview-main">
                  <section className="desktop-card">
                    <div className="card-topline">
                      <span className="soft-label">
                        <Monitor size={15} /> This Mac
                      </span>
                      <span className="online-label">
                        <span className="tiny-dot" />
                        {demo ? "Sample" : "Connected"}
                      </span>
                    </div>
                    <h2>{status?.name || "Your Mac"}</h2>

                    <div className="desktop-card-bottom">
                      <span>
                        <ShieldCheck size={15} />
                        {demo
                          ? "A preview of what’s possible"
                          : status?.screenPermission
                            ? "Ready to share your screen"
                            : "Screen permission needed"}
                      </span>
                      <Button
                        onClick={() => {
                          setTarget(null);
                          setTab("control");
                        }}
                      >
                        Open desktop <ArrowUpRight size={18} />
                      </Button>
                    </div>
                  </section>
                  <section className="apps-section">
                    <div className="section-head">
                      <h2>
                        Apps <span>{apps.length}</span>
                      </h2>
                      <button
                        className="text-link"
                        onClick={() => changeTab("apps")}
                      >
                        View all <ArrowRight size={15} />
                      </button>
                    </div>
                    <div className="app-grid">
                      {apps.slice(0, 6).map((app) => (
                        <button
                          className="app-tile"
                          key={app.bundleId}
                          onClick={() => openApp(app)}
                        >
                          <AppIcon app={app} />
                          <span>{app.name}</span>
                          <i className={app.active ? "active-dot" : ""} />
                        </button>
                      ))}
                    </div>
                    {!apps.length && (
                      <div className="empty">
                        Open an app on your Mac and it will appear here.
                      </div>
                    )}
                  </section>
                  <section className="files-section">
                    <div className="section-head">
                      <h2>Files</h2>
                      <button
                        className="text-link"
                        onClick={() => changeTab("files")}
                      >
                        Shared files <ArrowRight size={15} />
                      </button>
                    </div>
                    <div className="file-list">
                      {files.slice(0, 3).map((item) => (
                        <button
                          className="file-row"
                          key={item.path}
                          onClick={() =>
                            item.directory
                              ? (changeTab("files"), browse(item.path))
                              : shareFile(item)
                          }
                        >
                          <FileIcon item={item} />
                          <span className="file-detail">
                            <b>{item.name}</b>
                            <small>
                              {item.directory ? "Folder" : bytes(item.size)} ·{" "}
                              {status?.sharedFolder || "Shared folder"}
                            </small>
                          </span>
                          {item.directory ? (
                            <ChevronRight size={17} />
                          ) : (
                            <Download size={17} />
                          )}
                        </button>
                      ))}
                    </div>
                    {!files.length && (
                      <div className="empty">Your shared folder is empty.</div>
                    )}
                  </section>
                </div>
                <aside className="right-rail">
                  <section className="connection-card">
                    <span className="card-icon">
                      <Link2 size={20} />
                    </span>
                    <h3>iPhone connection</h3>
                    <p>
                      {status?.remoteEnabled
                        ? "Your Mac is available through your configured private connection."
                        : "Palm is running on this Mac. Pair your iPhone after enabling your private connection."}
                    </p>
                    <div className="connection-line">
                      <span>This Mac</span>
                      <i />
                      <Smartphone size={18} />
                    </div>
                    <div className="rail-data">
                      <span>Screen access</span>
                      <b>
                        {status?.screenPermission ? "Allowed" : "Needs setup"}
                      </b>
                    </div>
                    <div className="rail-data">
                      <span>Touch controls</span>
                      <b>
                        {status?.controlPermission ? "Allowed" : "Needs setup"}
                      </b>
                    </div>
                    <Button
                      secondary
                      onClick={local ? pairPhone : () => changeTab("settings")}
                    >
                      <Plus size={16} />{" "}
                      {local ? "Pair your iPhone" : "Connection details"}
                    </Button>
                  </section>
                  <section className="quick-card">
                    <div className="section-head">
                      <h3>Quick controls</h3>
                      <Command size={16} />
                    </div>
                    <button
                      onClick={() =>
                        demo
                          ? toast("Preview only. Your Mac stays unlocked.")
                          : setModal("lock")
                      }
                      disabled={!demo && !status?.power?.lock}
                    >
                      <Lock size={17} />
                      <span>Lock your Mac</span>
                      <ArrowUpRight size={15} />
                    </button>
                    <button
                      onClick={() => {
                        setTarget(null);
                        setTab("control");
                      }}
                    >
                      <MousePointer2 size={17} />
                      <span>Take control</span>
                      <ArrowUpRight size={15} />
                    </button>
                    <p>
                      Remote startup needs compatible hardware. It isn’t enabled
                      on this Mac.
                    </p>
                  </section>
                  <div className="rail-note">
                    <span>
                      Less reaching.
                      <br />
                      More doing.
                    </span>
                    <Mark />
                  </div>
                </aside>
              </div>
            </>
          )}
          {tab === "apps" && (
            <>
              <div className="page-heading">
                <div>
                  <div className="eyebrow">PICK UP THE THREAD</div>
                  <h1>
                    Your open apps<span className="lime">.</span>
                  </h1>
                  <p>The real apps running on your Mac.</p>
                </div>
              </div>
              <label className="search">
                <Search size={19} />
                <input
                  placeholder="Find an app…"
                  aria-label="Find an app"
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                />
                {query && (
                  <button
                    onClick={() => setQuery("")}
                    aria-label="Clear search"
                  >
                    <X size={16} />
                  </button>
                )}
              </label>
              <div className="apps-cards">
                {apps
                  .filter((a) =>
                    a.name.toLowerCase().includes(query.toLowerCase()),
                  )
                  .map((app) => (
                    <button
                      className="app-card"
                      key={app.bundleId}
                      onClick={() => openApp(app)}
                    >
                      <AppIcon app={app} />
                      <span>
                        <b>{app.name}</b>
                        <small>
                          {app.active
                            ? "Currently in front"
                            : `${app.windows?.length || 0} visible windows`}
                        </small>
                      </span>
                      <ArrowUpRight size={20} />
                    </button>
                  ))}
              </div>
              {apps.filter((a) =>
                a.name.toLowerCase().includes(query.toLowerCase()),
              ).length === 0 && (
                <div className="empty">
                  <Search />
                  <p>No apps match “{query}”.</p>
                </div>
              )}
            </>
          )}
          {tab === "files" && (
            <>
              <div className="page-heading">
                <div>
                  <div className="eyebrow">FROM DESKTOP TO POCKET</div>
                  <h1>
                    Right here<span className="lime">.</span>
                  </h1>
                  <p>Download a file or share it straight from your iPhone.</p>
                </div>
              </div>
              <div className="folder-path">
                <button onClick={() => browse("")}>
                  <Folder size={17} />
                  {status?.sharedFolder || "Shared"}
                </button>
                {folder && (
                  <>
                    <ChevronRight size={14} />
                    <span>{folder}</span>
                    <button
                      className="text-link"
                      onClick={() =>
                        browse(folder.split("/").slice(0, -1).join("/"))
                      }
                    >
                      <ArrowLeft size={16} /> Back
                    </button>
                  </>
                )}
              </div>
              <label className="search">
                <Search size={18} />
                <input
                  placeholder="Find a file in this folder…"
                  aria-label="Find a file"
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                />
              </label>
              <div className="file-list full-files">
                {files
                  .filter((f) =>
                    f.name.toLowerCase().includes(query.toLowerCase()),
                  )
                  .map((item) => (
                    <button
                      className="file-row"
                      key={item.path}
                      onClick={() => shareFile(item)}
                    >
                      <FileIcon item={item} />
                      <span className="file-detail">
                        <b>{item.name}</b>
                        <small>
                          {item.directory ? "Folder" : bytes(item.size)}
                        </small>
                      </span>
                      {item.directory ? (
                        <ChevronRight size={18} />
                      ) : (
                        <Share2 size={18} />
                      )}
                    </button>
                  ))}
              </div>
              {!files.filter((f) =>
                f.name.toLowerCase().includes(query.toLowerCase()),
              ).length && (
                <div className="empty">
                  <Folder />
                  <p>No files here yet.</p>
                </div>
              )}
              <p className="privacy-note">
                <ShieldCheck size={15} /> Only your selected shared folder is
                available. Hidden files stay private.
              </p>
            </>
          )}
          {tab === "control" && (
            <Control
              demo={demo}
              status={status}
              target={target}
              onBack={() => setTab("home")}
              onError={setError}
              onSetup={openSetup}
              local={local}
              onConnection={setConnected}
            />
          )}
          {tab === "settings" && (
            <>
              <div className="page-heading">
                <div>
                  <div className="eyebrow">ON YOUR TERMS</div>
                  <h1>
                    Make yourself at home<span className="lime">.</span>
                  </h1>
                  <p>Your computer. Your connection. Your control.</p>
                </div>
              </div>
              <div className="settings-grid">
                <section className="settings-card">
                  <div className="section-head">
                    <h2>Your Mac</h2>
                    <Monitor />
                  </div>
                  <div className="setting-row">
                    <span>Computer</span>
                    <b>{status?.name}</b>
                  </div>
                  <div className="setting-row">
                    <span>Screen recording</span>
                    <b>
                      {status?.screenPermission
                        ? "Allowed"
                        : "Needs permission"}
                    </b>
                  </div>
                  <div className="setting-row">
                    <span>Accessibility</span>
                    <b>
                      {status?.controlPermission
                        ? "Allowed"
                        : "Needs permission"}
                    </b>
                  </div>
                  <div className="setting-row">
                    <span>Shared folder</span>
                    <b>{status?.sharedFolder}</b>
                  </div>
                  {local && (
                    <Button secondary onClick={openSetup}>
                      Open Mac setup <Settings size={16} />
                    </Button>
                  )}
                </section>
                <section className="settings-card">
                  <div className="section-head">
                    <h2>Your connection</h2>
                    <ShieldCheck />
                  </div>
                  <p>
                    {demo
                      ? "You’re viewing an interactive design preview."
                      : status?.remoteEnabled
                        ? "Available through your configured private HTTPS address."
                        : "This preview is only available on the Mac itself. Private iPhone access needs a connection setup step."}
                  </p>
                  <div className="setting-row">
                    <span>Session lifetime</span>
                    <b>12 hours</b>
                  </div>
                  <div className="setting-row">
                    <span>Power on from off</span>
                    <b>Not configured</b>
                  </div>
                  {local && (
                    <Button onClick={pairPhone}>
                      Pair an iPhone <Plus size={17} />
                    </Button>
                  )}
                  <Button
                    secondary
                    onClick={async () => {
                      if (demo) return location.assign("/");
                      try {
                        await api("disconnect", {});
                        setPaired(false);
                        load();
                      } catch (e) {
                        setError(e.message);
                      }
                    }}
                  >
                    <LogOut size={16} /> Disconnect this device
                  </Button>
                </section>
              </div>
              <div className="honest-note">
                <h3>A first working build, with room to grow.</h3>
                <p>
                  Palm currently shares your main display or a visible app
                  window, controls your Mac, and downloads shared files. Audio,
                  uploads, automatic wake and full mobile layouts for every
                  desktop app are not included yet.
                </p>
              </div>
            </>
          )}
        </main>
        <footer className="workspace-footer">
          <span>
            <Mark /> Palm
          </span>
        </footer>
      </div>
      <nav className="mobile-nav" aria-label="Main navigation">
        {[
          ["home", Home, "Home"],
          ["apps", LayoutGrid, "Apps"],
          ["control", MousePointer2, "Control"],
          ["files", Folder, "Files"],
          ["settings", Settings, "Settings"],
        ].map(([id, Icon, label]) => (
          <button
            className={tab === id ? "active" : ""}
            key={id}
            onClick={() => {
              if (id === "control") setTarget(null);
              changeTab(id);
            }}
          >
            <Icon size={20} />
            <span>{label}</span>
          </button>
        ))}
      </nav>
      {notice && (
        <div className="toast" role="status">
          <CheckCircle2 size={18} />
          {notice}
        </div>
      )}
      {modal === "lock" && (
        <Modal title="Lock your Mac?" onClose={() => setModal(null)}>
          <p>
            Your Mac will lock immediately. You may need to unlock it before
            continuing your session.
          </p>
          <div className="modal-actions">
            <Button secondary onClick={() => setModal(null)}>
              Cancel
            </Button>
            <Button onClick={lockMac}>
              <Lock size={16} /> Lock Mac
            </Button>
          </div>
        </Modal>
      )}
      {modal === "pair" && (
        <Modal title="A little closer." onClose={() => setModal(null)}>
          <p>
            {pair?.url
              ? "Open your iPhone camera and scan to pair. Use the same private network connection as your Mac."
              : "Your pairing code is ready. Private iPhone access still needs to be enabled on this Mac."}
          </p>
          {qr && (
            <img className="qr" src={qr} alt="Scan with your iPhone to pair" />
          )}
          <div className="pair-display">
            {pair?.code?.match(/.{1,5}/g)?.join(" ")}
          </div>
          <p className="fine">
            Single use · expires{" "}
            {pair?.expires
              ? new Date(pair.expires).toLocaleTimeString([], {
                  hour: "2-digit",
                  minute: "2-digit",
                })
              : "in two minutes"}
          </p>
          {!pair?.url && (
            <div className="setup-note">
              <Link2 size={20} />
              <span>
                Palm is currently local. The private connection setup is
                documented in the project’s setup guide.
              </span>
            </div>
          )}
          <Button secondary onClick={pairPhone}>
            <RefreshCw size={16} /> New pairing code
          </Button>
        </Modal>
      )}
      {modal === "setup" && (
        <Modal title="A moment on your Mac." onClose={() => setModal(null)}>
          <p>
            macOS asks you to allow two things before your iPhone can see and
            control your computer.
          </p>
          {[
            [
              "screen",
              "Screen Recording",
              "Show your Mac on your iPhone.",
              setup?.status?.screenPermission,
            ],
            [
              "accessibility",
              "Accessibility",
              "Let your touches control the Mac.",
              setup?.status?.controlPermission,
            ],
          ].map(([kind, title, sub, ok]) => (
            <div className="permission" key={kind}>
              <span className={ok ? "permission-ok" : ""}>
                {ok ? <CheckCircle2 /> : <ShieldCheck />}
              </span>
              <div>
                <b>{title}</b>
                <small>{sub}</small>
              </div>
              <button className="text-link" onClick={() => permission(kind)}>
                {ok ? "Settings" : "Allow"} <ArrowUpRight size={15} />
              </button>
            </div>
          ))}
          <p className="fine">
            If macOS requests a restart after granting permission, stop and
            reopen Palm.
          </p>
          <Button
            secondary
            onClick={async () => {
              await load();
              setSetup(await api("local/setup"));
            }}
          >
            <RefreshCw size={16} /> Check permissions
          </Button>
          <form className="connection-setup" onSubmit={async (e) => {
            e.preventDefault();
            setBusy(true);
            try {
              await api("local/connection", { origin: connectionOrigin.trim() });
              setSetup(await api("local/setup"));
              await load();
              toast("Private address saved. Pair your iPhone using a fresh code.");
            } catch (e) { setError(e.message); }
            finally { setBusy(false); }
          }}>
            <h3>Private connection</h3>
            <p className="fine">Enter the HTTPS address supplied by Tailscale Serve on this Mac. Your iPhone must be connected to the same tailnet. Saving an address does not create a network service.</p>
            <label htmlFor="connection-origin">Private HTTPS address</label>
            <input id="connection-origin" type="url" value={connectionOrigin}
              placeholder="https://your-mac.your-tailnet.ts.net:8443"
              autoComplete="off" onChange={(e) => setConnectionOrigin(e.target.value)} />
            <Button secondary disabled={busy}>Save private address</Button>
          </form>
          <div className="paired-devices">
            <h3>Paired devices</h3>
            {setup?.devices?.map((d) => (
              <div className="device-row" key={d.id}>
                <Smartphone size={16} />
                <span>{d.name}</span>
                <button
                  className="text-link"
                  onClick={async () => {
                    await api("local/revoke", { id: d.id });
                    setSetup(await api("local/setup"));
                    toast("Device disconnected.");
                  }}
                >
                  Revoke
                </button>
              </div>
            ))}
          </div>
        </Modal>
      )}
    </div>
  );
}

function Control({
  demo,
  status,
  target,
  onBack,
  onError,
  onSetup,
  local,
  onConnection,
}) {
  const canvas = useRef(),
    socket = useRef(),
    decoder = useRef(),
    stage = useRef(),
    gesture = useRef(null),
    cursor = useRef({ x: 0.5, y: 0.5 }),
    configured = useRef(""),
    received = useRef(0);
  const [state, setState] = useState("idle"),
    [rtt, setRtt] = useState(null),
    [fps, setFps] = useState(null),
    [text, setText] = useState(""),
    [typing, setTyping] = useState(false),
    [mode, setMode] = useState("touch"),
    [zoom, setZoom] = useState(1),
    [failure, setFailure] = useState(""),
    [actions, setActions] = useState(null),
    [actionsBusy, setActionsBusy] = useState(false);
  function send(x) {
    if (socket.current?.readyState === 1)
      socket.current.send(JSON.stringify(x));
  }
  function stop() {
    socket.current?.close();
    socket.current = null;
    if (decoder.current?.state !== "closed") decoder.current?.close();
    decoder.current = null;
    configured.current = "";
    setState("idle");
    setRtt(null);
    setFps(null);
    onConnection(false);
  }
  useEffect(
    () => () => {
      socket.current?.close();
      if (decoder.current?.state !== "closed") decoder.current?.close();
      onConnection(false);
    },
    [],
  );
  useEffect(() => {
    if (state !== "live") return;
    const id = setInterval(() => {
      send({ op: "ping", at: performance.now() });
      setFps(received.current);
      received.current = 0;
    }, 1000);
    return () => clearInterval(id);
  }, [state]);
  function start() {
    if (demo) {
      setState("preview");
      return;
    }
    if (!("VideoDecoder" in window)) {
      setFailure(
        "This browser cannot decode the live stream. Use a current Safari version over HTTPS.",
      );
      return;
    }
    setFailure("");
    setState("connecting");
    const ws = new WebSocket(
      `${location.protocol === "https:" ? "wss:" : "ws:"}//${location.host}/socket`,
    );
    ws.binaryType = "arraybuffer";
    socket.current = ws;
    let starting = setTimeout(() => {
      setFailure(
        "The Mac did not start sharing. Check its permissions and try again.",
      );
      stop();
    }, 18000);
    ws.onmessage = async (e) => {
      if (typeof e.data === "string") {
        const x = JSON.parse(e.data);
        if (x.event === "connected") {
          send({ op: "start", windowId: target?.windowId || 0 });
        }
        if (x.event === "config") {
          const signature = x.codec + x.description;
          if (
            configured.current === signature &&
            decoder.current?.state === "configured"
          )
            return;
          if (decoder.current?.state !== "closed") decoder.current?.close();
          const d = new VideoDecoder({
            output: (frame) => {
              const c = canvas.current;
              if (c) {
                c.width = frame.displayWidth;
                c.height = frame.displayHeight;
                c.getContext("2d", { alpha: false }).drawImage(frame, 0, 0);
                received.current++;
              }
              frame.close();
              setState("live");
              onConnection(true);
              clearTimeout(starting);
            },
            error: () => {
              setFailure("The video decoder stopped. Reconnect to continue.");
              stop();
            },
          });
          decoder.current = d;
          try {
            const config = {
              codec: x.codec,
              description: Uint8Array.from(atob(x.description), (c) =>
                c.charCodeAt(0),
              ),
              optimizeForLatency: true,
            };
            const supported = await VideoDecoder.isConfigSupported(config);
            if (!supported.supported) throw new Error();
            d.configure(config);
            configured.current = signature;
          } catch {
            setFailure("This browser cannot decode the Mac video format.");
            stop();
          }
        }
        if (x.event === "pong") setRtt(Math.round(performance.now() - x.at));
        if (x.event === "error") {
          setFailure(x.message);
          clearTimeout(starting);
          stop();
        }
        if (x.event === "stopped") {
          setFailure("Sharing was stopped on the Mac.");
          clearTimeout(starting);
          stop();
        }
      } else {
        const d = decoder.current;
        if (d?.state !== "configured") return;
        const view = new DataView(e.data),
          isKey = view.getUint8(0) === 1;
        if (d.decodeQueueSize > 4) {
          send({ op: "keyframe" });
          configured.current = "";
          d.reset();
          return;
        }
        try {
          d.decode(
            new EncodedVideoChunk({
              type: isKey ? "key" : "delta",
              timestamp: view.getFloat64(1),
              data: new Uint8Array(e.data, 9),
            }),
          );
        } catch {
          send({ op: "keyframe" });
        }
      }
    };
    ws.onerror = () => {
      setFailure(
        "Could not open a control session. Another device may already be connected.",
      );
      clearTimeout(starting);
      stop();
    };
    ws.onclose = () => {
      clearTimeout(starting);
      if (socket.current === ws) {
        socket.current = null;
        setState("idle");
        setRtt(null);
        setFps(null);
        onConnection(false);
      }
    };
  }
  function point(e) {
    const r = canvas.current.getBoundingClientRect();
    return {
      x: (e.clientX - r.left) / r.width,
      y: (e.clientY - r.top) / r.height,
    };
  }
  function down(e) {
    if (state !== "live" || !status?.controlPermission) return;
    gesture.current = {
      x: e.clientX,
      y: e.clientY,
      lastX: e.clientX,
      lastY: e.clientY,
      time: Date.now(),
      moved: false,
    };
    e.currentTarget.setPointerCapture(e.pointerId);
  }
  function move(e) {
    const g = gesture.current;
    if (!g) return;
    const dx = e.clientX - g.lastX,
      dy = e.clientY - g.lastY;
    g.lastX = e.clientX;
    g.lastY = e.clientY;
    if (Math.hypot(e.clientX - g.x, e.clientY - g.y) > 6) g.moved = true;
    if (g.moved) {
      if (mode === "trackpad") {
        cursor.current = {
          x: Math.max(0, Math.min(1, cursor.current.x + dx / 600)),
          y: Math.max(0, Math.min(1, cursor.current.y + dy / 600)),
        };
        send({ op: "pointer", action: "move", ...cursor.current });
      } else send({ op: "scroll", dx, dy });
    }
  }
  function up(e) {
    const g = gesture.current;
    gesture.current = null;
    if (!g || g.moved) return;
    const p = mode === "trackpad" ? cursor.current : point(e);
    send({
      op: "pointer",
      action: Date.now() - g.time > 550 ? "right" : "click",
      ...p,
    });
  }
  async function loadActions() {
    setActionsBusy(true);
    try {
      setActions(
        demo
          ? { app: "Sample app", actions: [] }
          : await api("command", { op: "actions" }),
      );
    } catch (e) {
      setFailure(e.message);
    } finally {
      setActionsBusy(false);
    }
  }
  async function runAction(actionId) {
    try {
      await api("command", { op: "action", actionId });
      await loadActions();
    } catch (e) {
      setFailure(e.message);
    }
  }
  function submitText(e) {
    e.preventDefault();
    if (!text) return;
    send({ op: "text", text });
    setText("");
  }
  const live = state === "live";
  return (
    <section className="remote">
      <div className="remote-heading">
        <button
          className="icon-button"
          onClick={onBack}
          aria-label="Back to overview"
        >
          <ArrowLeft size={20} />
        </button>
        <div>
          <h2>{target?.name || "Your desktop"}</h2>
          <span>
            {live ? (
              <>
                <span className="tiny-dot" /> Live on your Mac
              </>
            ) : state === "connecting" ? (
              "Starting your session…"
            ) : (
              "Bring it into your hands"
            )}
          </span>
        </div>
        <div className="live-metrics">
          {rtt !== null && (
            <span>
              <Signal size={14} />
              {rtt} ms
            </span>
          )}
          {fps !== null && <span>{fps} fps</span>}
        </div>
        {live && (
          <button className="text-link" onClick={stop}>
            End <X size={15} />
          </button>
        )}
      </div>
      {failure && live && (
        <div className="alert" role="alert">
          <AlertCircle size={16} />
          {failure}
        </div>
      )}
      <div className={"remote-stage " + (live ? "is-live" : "")} ref={stage}>
        <div className="canvas-wrap" style={{ transform: `scale(${zoom})` }}>
          <canvas
            ref={canvas}
            width="1280"
            height="800"
            onPointerDown={down}
            onPointerMove={move}
            onPointerUp={up}
            onPointerCancel={() => (gesture.current = null)}
            onContextMenu={(e) => e.preventDefault()}
            aria-label="Your Mac screen. Tap to click, drag to scroll, hold to right-click."
          />
        </div>
        {!live && (
          <div className="stage-overlay">
            <span className="stage-glyph">
              <Monitor size={32} />
            </span>
            <h2>
              {state === "preview"
                ? "Your desktop belongs here."
                : state === "connecting"
                  ? "One moment."
                  : "A whole Mac. In your hand."}
            </h2>
            <p>
              {failure ||
                (state === "preview"
                  ? "This is an interface preview. Connect your Mac to see and control its real screen."
                  : !status?.screenPermission
                    ? "Allow Screen Recording on your Mac to start your first session."
                    : "Open a live view, then tap, scroll and type from your phone.")}
            </p>
            {state === "connecting" ? (
              <LoaderCircle className="spin" />
            ) : !demo && !status?.screenPermission && local ? (
              <Button onClick={onSetup}>
                Set up screen access <ArrowUpRight size={16} />
              </Button>
            ) : (
              <Button onClick={start}>
                <Play size={16} />
                {failure
                  ? "Try again"
                  : demo
                    ? "Preview control view"
                    : "Start session"}
              </Button>
            )}
          </div>
        )}
      </div>
      {live && !status?.controlPermission && (
        <div className="view-only">
          <Eye size={16} /> View only. Allow Accessibility on the Mac to control
          it.
          {local && (
            <button className="text-link" onClick={onSetup}>
              Set up
            </button>
          )}
        </div>
      )}
      <div className="control-toolbar">
        <div className="segmented">
          <button
            className={mode === "touch" ? "active" : ""}
            onClick={() => setMode("touch")}
          >
            <Hand size={17} />
            <span>Touch</span>
          </button>
          <button
            className={mode === "trackpad" ? "active" : ""}
            onClick={() => setMode("trackpad")}
          >
            <MousePointer2 size={17} />
            <span>Trackpad</span>
          </button>
        </div>
        <div className="zoom-controls">
          <button
            className="icon-button"
            disabled={zoom <= 1}
            aria-label="Zoom out"
            onClick={() => setZoom(Math.max(1, zoom - 0.25))}
          >
            <Minus size={17} />
          </button>
          <span>{Math.round(zoom * 100)}%</span>
          <button
            className="icon-button"
            disabled={zoom >= 2}
            aria-label="Zoom in"
            onClick={() => setZoom(Math.min(2, zoom + 0.25))}
          >
            <Plus size={17} />
          </button>
        </div>
        <button
          className={"keyboard-button " + (typing ? "active" : "")}
          onClick={() => setTyping(!typing)}
        >
          <Keyboard size={19} />
          <span>Type</span>
        </button>
      </div>
      <div className="native-actions">
        <button
          className="text-link"
          onClick={() => (actions ? setActions(null) : loadActions())}
          disabled={!live || !status?.controlPermission}
        >
          <LayoutGrid size={16} />
          {actions ? "Hide app controls" : "Show app controls"}{" "}
          <ChevronDown size={15} />
        </button>
        {actionsBusy && <LoaderCircle size={16} className="spin" />}
        {actions && (
          <div className="actions-panel">
            <div className="section-head">
              <h3>{actions.app} · App controls</h3>
              <button
                className="icon-button"
                onClick={loadActions}
                aria-label="Refresh app controls"
              >
                <RefreshCw size={15} />
              </button>
            </div>
            <p>Buttons from your Mac, sized for your thumb.</p>
            <div className="action-buttons">
              {actions.actions.map((a) => (
                <button key={a.id} onClick={() => runAction(a.id)}>
                  {a.title}
                  <ArrowUpRight size={15} />
                </button>
              ))}
            </div>
            {!actions.actions.length && (
              <p>
                This app does not expose any named buttons in its current
                window. Use the screen or keyboard shortcuts below.
              </p>
            )}
          </div>
        )}
      </div>
      {mode === "trackpad" && (
        <div
          className="trackpad"
          onPointerDown={down}
          onPointerMove={move}
          onPointerUp={up}
          onPointerCancel={() => (gesture.current = null)}
        >
          <span>Move here to guide the cursor · tap to click</span>
          <div className="trackpad-cross" />
        </div>
      )}
      {typing && (
        <form className="typing-panel" onSubmit={submitText}>
          <label htmlFor="remote-text">Type on your Mac</label>
          <div>
            <input
              id="remote-text"
              autoFocus
              placeholder="Your iPhone keyboard, your Mac app…"
              value={text}
              maxLength={4000}
              onChange={(e) => setText(e.target.value)}
              disabled={!live || !status?.controlPermission}
            />
            <Button disabled={!live || !text} type="submit">
              <ArrowRight size={18} />
            </Button>
          </div>
          <p>
            Tap the destination text field on your Mac first. Use your iPhone
            keyboard’s microphone to dictate.
          </p>
        </form>
      )}
      <div className="shortcut-strip">
        {[
          ["escape", "esc"],
          ["tab", "tab"],
          ["enter", "return ↵"],
          ["backspace", "⌫"],
          ["save", "⌘ S"],
          ["undo", "⌘ Z"],
          ["copy", "⌘ C"],
          ["paste", "⌘ V"],
          ["selectAll", "⌘ A"],
          ["find", "⌘ F"],
        ].map(([key, label]) => (
          <button
            key={key}
            onClick={() => send({ op: "key", key })}
            disabled={!live || !status?.controlPermission}
          >
            {label}
          </button>
        ))}
      </div>
      <div className="gesture-guide">
        <span>
          <Hand size={16} /> Tap to click
        </span>
        <span>Drag to scroll</span>
        <span>Hold to right-click</span>
        <span>Rotate your iPhone for more room</span>
      </div>
    </section>
  );
}

export default App;
